<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRmWdRGl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRmWdRGl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRmWdRGl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRmWdRGl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRmWdRGl\App_KernelDevDebugContainer([
    'container.build_hash' => 'RmWdRGl',
    'container.build_id' => '974b174f',
    'container.build_time' => 1667399227,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRmWdRGl');
