<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'client_php' => [['nom'], ['_controller' => ['App\\Controller\\ClientController', 'info']], ['nom' => '[A-Za-z]+(?:-?[A-Za-z]+)+'], [['variable', '/', '[A-Za-z]+(?:-?[A-Za-z]+)+', 'nom', true], ['text', '/client/prenom/php']], [], [], []],
    'app_client_info' => [['nom'], ['_controller' => 'App\\Controller\\ClientController::info'], ['nom' => '[A-Za-z]+(?:-?[A-Za-z]+)+'], [['variable', '/', '[A-Za-z]+(?:-?[A-Za-z]+)+', 'nom', true], ['text', '/client/prenom']], [], [], []],
    'client_photo' => [['nom'], ['_controller' => 'App\\Controller\\ClientController::photo'], [], [['variable', '/', '[^/]++', 'nom', true], ['text', '/client/photo']], [], [], []],
    'image' => [[], ['_controller' => 'App\\Controller\\ImageController::index'], [], [['text', '/']], [], [], []],
    'image_show' => [['img'], ['_controller' => 'App\\Controller\\ImageController::image'], [], [['variable', '/', '[^/]++', 'img', true], ['text', '/images']], [], [], []],
    'client_yaml' => [['nom'], ['_controller' => 'App\\Controller\\ClientController::info'], ['nom' => '[A-Za-z]+(?:-?[A-Za-z]+)+'], [['variable', '/', '[A-Za-z]+(?:-?[A-Za-z]+)+', 'nom', true], ['text', '/client/prenom/yaml']], [], [], []],
];
